-- MySQL Script generated by MySQL Workbench
-- Fri Jul 11 22:49:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pacientes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pacientes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pacientes` DEFAULT CHARACTER SET utf8 ;
USE `pacientes` ;

-- -----------------------------------------------------
-- Table `pacientes`.`tb_classe_trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pacientes`.`tb_classe_trabalho` (
  `cod_classe_trabalho` INT NOT NULL AUTO_INCREMENT,
  `classe_trabalho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_classe_trabalho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pacientes`.`tb_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pacientes`.`tb_estado` (
  `cod_estado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `sigla` CHAR(2) NOT NULL,
  `regiao` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pacientes`.`tb_escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pacientes`.`tb_escolaridade` (
  `cod_escolaridade` INT NOT NULL AUTO_INCREMENT,
  `escolaridade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_escolaridade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pacientes`.`tb_raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pacientes`.`tb_raca` (
  `cod_raca` INT NOT NULL AUTO_INCREMENT,
  `raca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_raca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pacientes`.`tb_estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pacientes`.`tb_estado_civil` (
  `cod_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_estado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pacientes`.`tb_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pacientes`.`tb_paciente` (
  `cod_paciente` INT NOT NULL AUTO_INCREMENT,
  `cod_estado_civil` INT NOT NULL,
  `cod_raca` INT NOT NULL,
  `cod_escolaridade` INT NOT NULL,
  `cod_classe_trabalho` INT NOT NULL,
  `cod_estado` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `qtd_filho` INT NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `peso` DECIMAL(10,2) NOT NULL,
  `colesterol` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`cod_paciente`),
  INDEX `fk_tb_paciente_tb_estado_civil_idx` (`cod_estado_civil` ASC) VISIBLE,
  INDEX `fk_tb_paciente_tb_raca1_idx` (`cod_raca` ASC) VISIBLE,
  INDEX `fk_tb_paciente_tb_escolaridade1_idx` (`cod_escolaridade` ASC) VISIBLE,
  INDEX `fk_tb_paciente_tb_estado1_idx` (`cod_estado` ASC) VISIBLE,
  INDEX `fk_tb_paciente_tb_classe_trabalho1_idx` (`cod_classe_trabalho` ASC) VISIBLE,
  CONSTRAINT `fk_tb_paciente_tb_estado_civil`
    FOREIGN KEY (`cod_estado_civil`)
    REFERENCES `pacientes`.`tb_estado_civil` (`cod_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_paciente_tb_raca1`
    FOREIGN KEY (`cod_raca`)
    REFERENCES `pacientes`.`tb_raca` (`cod_raca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_paciente_tb_escolaridade1`
    FOREIGN KEY (`cod_escolaridade`)
    REFERENCES `pacientes`.`tb_escolaridade` (`cod_escolaridade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_paciente_tb_estado1`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `pacientes`.`tb_estado` (`cod_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_paciente_tb_classe_trabalho1`
    FOREIGN KEY (`cod_classe_trabalho`)
    REFERENCES `pacientes`.`tb_classe_trabalho` (`cod_classe_trabalho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
